spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopmanager?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
logging:
  level:
    com.hwua.springbootmybatis: debug
  file: D:\logs\shopmanager.log